package com.stazo.project_18;

import com.firebase.client.Firebase;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Created by ericzhang on 4/25/16.
 */
public class User {
    private String ID; // generated by facebook api
    private String name;
    private ArrayList<String> myEvents;
    // can add further stuff later such as event host list, rating, history, upcoming event lists


    /**
     * Default constructor for firebase
     */
    public User() {
    }

    // for new users
    public User(String user_id, String name) {
        this.ID = user_id;
        this.name = name;
        this.myEvents = new ArrayList<String>();
    }

    // for existing users
    public User(String user_id, String name, ArrayList<String> myEvents) {
        this.ID = user_id;
        this.name = name;
        this.myEvents = myEvents;
    }

    // constructor with HashMap
    public User(HashMap<String, Object> userMap) {
        this.name = (String) userMap.get("name");
        System.out.println(name + '\n');
        this.ID = (String) userMap.get("id");
        // remove this after all users have myEvents reference in firebase
        if (userMap.containsKey("myEvents")) {
            this.myEvents = (ArrayList<String>) userMap.get("myEvents");
            // TODO add myEvents initialization
        }
    }

    /**
     * Pushes the user's info onto Firebase
     */
    private void pushToFirebase(Firebase ref) {
        Firebase userRef = ref.child("Users").child(ID);
        userRef.setValue(this); // set the value for the user_id child to this user
    }

    //Getters and setters
    public String getID() {
        return this.ID;
    }

    public String getName() {
        return this.name;
    }

    public ArrayList<String> getMyEvents() {
        return this.myEvents;
    }



    public void setMyEvents(ArrayList<String> events) { myEvents = events; }

    public void setID(String user_id) {
        this.ID = user_id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void addEvent(String a) {
        myEvents.add(a);
    }

}
