package com.stazo.project_18;

import com.firebase.client.Firebase;

/**
 * Created by ericzhang on 4/25/16.
 */
public class User {
    private String user_id; // generated by facebook api
    private String name;
    // can add further stuff later such as event host list, rating, history, upcoming event lists


    /**
     * Default constructor for firebase
     */
    public User() {
    }

    public User(String user_id, String name) {
        this.user_id = user_id;
        this.name = name;
    }

    /**
     * Pushes the user's info onto Firebase
     */
    private void pushToFirebase(Firebase ref) {
        Firebase userRef = ref.child("Users").child(user_id);
        userRef.setValue(this); // set the value for the user_id child to this user
    }

    //Getters and setters
    public String getID() {
        return this.user_id;
    }

    public String getName() {
        return this.name;
    }

    public void setID(String user_id) {
        this.user_id = user_id;
    }

    public void setName(String name) {
        this.name = name;
    }
}
